### ISSUE TITLE
404 Error File not found

### ISSUE THREAD

**Issue by verifierlife** [sakibccr/pristine#3]
Hi, I clone the pristine in "myname.github.io/themes/"  folder and also, I have changed the config.toml file.  When I use `hugo server`,  it shows correct.  After that I deploy my site using `hugo`. 
Then I visit my https://myname.github.io.  Unfortunately, it shows 404 Error:

-404
-File not found

-The site configured at this address does not contain the requested file.

-If this is your site, make sure that the filename case matches the URL.
-For root URLs (like http://example.com/) you must provide an index.html file.

-Read the full documentation for more information about using GitHub Pages

What's the reason? Who can help me solve it?  Thank you very much.
(BTW, there is no index.html in myname.github.io folder. Is it essential? )

**Comment by sakibccr** [comment]
A `index.html` file is essential. When you visit your site, that file will be served first.
Also you must build the site after adding a new theme by running `hugo` command, without the `server` part. Then the site builds into a `public/` directory. You should deploy that directory. Not anything else. Please read the [docs](https://gohugo.io/getting-started/usage/) first.

**Comment by sakibccr** [comment]
I am closing this.
