### ISSUE TITLE
Internal links open in new tabs

### ISSUE THREAD

**Issue by aschwa** [sakibccr/pristine#5]
In my config.toml, I have some internal links. They open in new tabs. How do I adjust this to open in the same tab?

[[menu.projects]]
  name = "Press"
  url = "/press"
  weight = 2

**Comment by sakibccr** [comment]
In [this](https://github.com/sakibccr/pristine/blob/3376365358139c2251669d0f41d940c35641060a/layouts/partials/sidemenu.html#L28) line remove `target="_blank"` and make it looks like this:

`<li><a href="{{.URL}}" target="_blank">{{ .Name }}</li>`

That should do it.
